"""
01_temporal_structure.py

Temporal Structure Analysis
===========================

Purpose
-------
Analyze the temporal organization of the PhySense-Human dataset
before performing image-level similarity, motion, or correspondence
analysis.

This script:

1. Locates the dataset master_index.csv automatically.
2. Loads only the columns required for temporal analysis.
3. Groups frames by source video.
4. Sorts frames by frame_id.
5. Computes temporal/frame-ID gaps.
6. Computes frames per video.
7. Estimates sequence duration.
8. Detects videos split across multiple dataset shards.
9. Builds adjacent temporal frame pairs.
10. Produces summary CSV/JSON files.
11. Produces diagnostic figures.

Important
---------
frame_id is treated as the temporal ordering variable.

If the original extraction process sampled approximately one frame
per second, EXPECTED_FRAME_INTERVAL_SECONDS can be set to 1.0.

The script does NOT assume that frame_id itself is a timestamp.
It only uses frame_id to establish temporal order and calculate
frame-ID differences.

Outputs
-------
results/temporal_statistics/
    temporal_summary.json
    video_temporal_statistics.csv
    frame_pair_statistics.csv
    temporal_gaps.csv

results/figures/
    frames_per_video_temporal.png
    frame_gap_distribution.png
    estimated_video_duration.png
    videos_per_split_temporal.png
    videos_spanning_shards.png

Author
------
PhySense-Human Research Pipeline
"""

from __future__ import annotations

import json
import math
import sys
import time
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt


# ============================================================
# CONFIGURATION
# ============================================================

EXPECTED_FRAME_INTERVAL_SECONDS = 1.0

# Maximum number of videos shown individually in some figures.
MAX_INDIVIDUAL_VIDEOS_IN_PLOT = 200

# Only these columns are required from master_index.csv.
REQUIRED_COLUMNS = [
    "shard",
    "split",
    "video_id",
    "frame_id",
    "hr_filename",
]


# ============================================================
# TERMINAL UTILITIES
# ============================================================

def print_header(title: str) -> None:
    print()
    print("=" * 78)
    print(title)
    print("=" * 78)


def print_step(message: str) -> None:
    print()
    print("-" * 78)
    print(message)
    print("-" * 78)


def format_number(value) -> str:
    if isinstance(value, (int, np.integer)):
        return f"{value:,}"

    if isinstance(value, (float, np.floating)):
        return f"{value:,.4f}"

    return str(value)


# ============================================================
# PATH DISCOVERY
# ============================================================

def find_project_root() -> Path:
    """
    Find the project root by searching upward for:
        01_dataset_audit
    and/or
        02_temporal_redundancy
    """

    current = Path(__file__).resolve().parent

    candidates = [current] + list(current.parents)

    for path in candidates:
        if (
            (path / "01_dataset_audit").exists()
            and (path / "02_temporal_redundancy").exists()
        ):
            return path

    raise FileNotFoundError(
        "Could not locate project root.\n"
        "Expected a directory containing both:\n"
        "  01_dataset_audit/\n"
        "  02_temporal_redundancy/"
    )


def find_master_index(project_root: Path) -> Path:
    """
    Locate the master_index.csv generated by the integrity audit.
    """

    candidates = [
        project_root
        / "01_dataset_audit"
        / "results"
        / "integrity"
        / "master_index.csv",

        project_root
        / "01_dataset_audit"
        / "01_dataset_audit"
        / "results"
        / "integrity"
        / "master_index.csv",
    ]

    for path in candidates:
        if path.exists():
            return path

    # Fallback recursive search
    matches = list(project_root.rglob("master_index.csv"))

    if len(matches) == 1:
        return matches[0]

    if len(matches) > 1:
        print("Multiple master_index.csv files found:")

        for m in matches:
            print(f"  - {m}")

        raise RuntimeError(
            "Multiple master_index.csv files found. "
            "Please keep only the intended dataset index."
        )

    raise FileNotFoundError(
        "master_index.csv was not found.\n"
        "Expected location:\n"
        "01_dataset_audit/results/integrity/master_index.csv"
    )


# ============================================================
# OUTPUT DIRECTORIES
# ============================================================

def create_output_directories(project_root: Path) -> Dict[str, Path]:

    temporal_root = project_root / "02_temporal_redundancy"

    statistics_dir = (
        temporal_root
        / "results"
        / "temporal_statistics"
    )

    figures_dir = (
        temporal_root
        / "results"
        / "figures"
    )

    statistics_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    figures_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    return {
        "root": temporal_root,
        "statistics": statistics_dir,
        "figures": figures_dir,
    }


# ============================================================
# DATA LOADING
# ============================================================

def load_master_index(master_index_path: Path) -> pd.DataFrame:

    print_step("Loading master dataset index")

    print(f"Master index:")
    print(f"  {master_index_path}")

    print()
    print("Reading required columns only...")

    try:
        df = pd.read_csv(
            master_index_path,
            usecols=REQUIRED_COLUMNS,
            low_memory=False,
        )

    except ValueError as exc:
        raise RuntimeError(
            "The master_index.csv does not contain all required "
            f"columns:\n{REQUIRED_COLUMNS}\n\n"
            f"Original error:\n{exc}"
        )

    print(
        f"Rows loaded: {format_number(len(df))}"
    )

    # --------------------------------------------------------
    # Basic cleaning
    # --------------------------------------------------------

    missing_before = df[
        ["shard", "split", "video_id", "frame_id"]
    ].isna().any(axis=1).sum()

    if missing_before > 0:
        print(
            f"WARNING: {format_number(missing_before)} rows contain "
            "missing temporal metadata."
        )

        df = df.dropna(
            subset=[
                "shard",
                "split",
                "video_id",
                "frame_id",
            ]
        ).copy()

    # Convert frame_id to numeric
    df["frame_id"] = pd.to_numeric(
        df["frame_id"],
        errors="coerce",
    )

    invalid_frame_ids = df["frame_id"].isna().sum()

    if invalid_frame_ids > 0:

        print(
            f"WARNING: {format_number(invalid_frame_ids)} rows have "
            "invalid frame_id values and will be removed."
        )

        df = df.dropna(
            subset=["frame_id"]
        ).copy()

    df["frame_id"] = df["frame_id"].astype(np.int64)

    # Normalize strings
    df["video_id"] = df["video_id"].astype(str)
    df["split"] = df["split"].astype(str)
    df["shard"] = df["shard"].astype(str)

    print(
        f"Valid temporal rows: {format_number(len(df))}"
    )

    return df


# ============================================================
# DUPLICATE CHECK
# ============================================================

def check_duplicate_temporal_identities(
    df: pd.DataFrame,
) -> pd.DataFrame:

    print_step("Checking duplicate temporal identities")

    duplicated = (
        df
        .duplicated(
            subset=[
                "video_id",
                "frame_id",
            ],
            keep=False,
        )
    )

    duplicates = df.loc[duplicated].copy()

    print(
        "Duplicate (video_id, frame_id) records:",
        format_number(len(duplicates)),
    )

    if len(duplicates) > 0:
        print(
            "WARNING: Duplicate temporal identities detected."
        )

    return duplicates


# ============================================================
# VIDEO TEMPORAL STATISTICS
# ============================================================

def compute_video_temporal_statistics(
    df: pd.DataFrame,
) -> Tuple[pd.DataFrame, pd.DataFrame]:

    print_step("Computing video-level temporal statistics")

    # Sort globally first.
    df = df.sort_values(
        [
            "video_id",
            "frame_id",
        ]
    ).reset_index(drop=True)

    # --------------------------------------------------------
    # Frame-to-frame differences
    # --------------------------------------------------------

    df["frame_id_diff"] = (
        df
        .groupby("video_id")["frame_id"]
        .diff()
    )

    # First frame of every video has no previous frame.
    df["is_first_frame"] = (
        df["frame_id_diff"].isna()
    )

    df["is_adjacent"] = (
        df["frame_id_diff"] == 1
    )

    df["has_frame_gap"] = (
        df["frame_id_diff"].fillna(1) > 1
    )

    # Negative differences should not happen after sorting.
    df["has_backward_jump"] = (
        df["frame_id_diff"].fillna(0) < 0
    )

    # --------------------------------------------------------
    # Aggregate per video
    # --------------------------------------------------------

    rows = []

    for video_id, group in df.groupby(
        "video_id",
        sort=False,
    ):

        frame_ids = group["frame_id"].to_numpy()

        n_frames = len(frame_ids)

        min_frame_id = int(frame_ids.min())
        max_frame_id = int(frame_ids.max())

        span = max_frame_id - min_frame_id + 1

        expected_transitions = max(
            n_frames - 1,
            0,
        )

        observed_transitions = expected_transitions

        if expected_transitions > 0:

            diffs = np.diff(frame_ids)

            adjacent_transitions = int(
                np.sum(diffs == 1)
            )

            gap_count = int(
                np.sum(diffs > 1)
            )

            backward_count = int(
                np.sum(diffs < 0)
            )

            mean_gap = float(
                np.mean(diffs)
            )

            median_gap = float(
                np.median(diffs)
            )

            max_gap = int(
                np.max(diffs)
            )

        else:

            adjacent_transitions = 0
            gap_count = 0
            backward_count = 0
            mean_gap = 0.0
            median_gap = 0.0
            max_gap = 0

        continuity_ratio = (
            adjacent_transitions / expected_transitions
            if expected_transitions > 0
            else 1.0
        )

        # Approximate duration.
        #
        # This is based on frame-ID span and the configured
        # expected sampling interval.
        estimated_duration_seconds = (
            span * EXPECTED_FRAME_INTERVAL_SECONDS
        )

        estimated_duration_minutes = (
            estimated_duration_seconds / 60.0
        )

        # ----------------------------------------------------
        # Split / shard information
        # ----------------------------------------------------

        splits = sorted(
            group["split"].unique().tolist()
        )

        shards = sorted(
            group["shard"].unique().tolist()
        )

        rows.append(
            {
                "video_id": video_id,

                "split": "|".join(splits),

                "num_shards": len(shards),

                "shards": "|".join(shards),

                "num_frames": n_frames,

                "min_frame_id": min_frame_id,

                "max_frame_id": max_frame_id,

                "frame_id_span": span,

                "expected_transitions": expected_transitions,

                "adjacent_transitions": adjacent_transitions,

                "gap_count": gap_count,

                "backward_jump_count": backward_count,

                "continuity_ratio": continuity_ratio,

                "mean_frame_id_gap": mean_gap,

                "median_frame_id_gap": median_gap,

                "max_frame_id_gap": max_gap,

                "estimated_duration_seconds":
                    estimated_duration_seconds,

                "estimated_duration_minutes":
                    estimated_duration_minutes,

                "spans_multiple_shards":
                    len(shards) > 1,

                "has_frame_id_gap":
                    gap_count > 0,
            }
        )

    video_stats = pd.DataFrame(rows)

    # --------------------------------------------------------
    # Temporal gap table
    # --------------------------------------------------------

    gap_rows = []

    for video_id, group in df.groupby(
        "video_id",
        sort=False,
    ):

        group = group.sort_values(
            "frame_id"
        )

        frame_ids = group["frame_id"].to_numpy()

        if len(frame_ids) < 2:
            continue

        diffs = np.diff(frame_ids)

        gap_indices = np.where(
            diffs > 1
        )[0]

        for idx in gap_indices:

            gap_rows.append(
                {
                    "video_id": video_id,

                    "previous_frame_id":
                        int(frame_ids[idx]),

                    "next_frame_id":
                        int(frame_ids[idx + 1]),

                    "frame_id_gap":
                        int(diffs[idx]),

                    "missing_frame_count":
                        int(diffs[idx] - 1),
                }
            )

    gap_df = pd.DataFrame(
        gap_rows,
        columns=[
            "video_id",
            "previous_frame_id",
            "next_frame_id",
            "frame_id_gap",
            "missing_frame_count",
        ],
    )

    return video_stats, gap_df


# ============================================================
# ADJACENT TEMPORAL PAIRS
# ============================================================

def build_adjacent_frame_statistics(
    df: pd.DataFrame,
) -> pd.DataFrame:

    print_step("Building adjacent temporal frame statistics")

    df = df.sort_values(
        [
            "video_id",
            "frame_id",
        ]
    ).reset_index(drop=True)

    rows = []

    for video_id, group in df.groupby(
        "video_id",
        sort=False,
    ):

        group = group.sort_values(
            "frame_id"
        ).reset_index(drop=True)

        if len(group) < 2:
            continue

        frame_ids = group["frame_id"].to_numpy()

        for i in range(len(group) - 1):

            frame_a = int(frame_ids[i])
            frame_b = int(frame_ids[i + 1])

            gap = frame_b - frame_a

            rows.append(
                {
                    "video_id": video_id,

                    "split":
                        group.loc[i, "split"],

                    "shard_a":
                        group.loc[i, "shard"],

                    "shard_b":
                        group.loc[i + 1, "shard"],

                    "frame_id_a":
                        frame_a,

                    "frame_id_b":
                        frame_b,

                    "frame_id_distance":
                        gap,

                    "is_temporally_adjacent":
                        gap == 1,

                    "estimated_time_distance_seconds":
                        gap
                        * EXPECTED_FRAME_INTERVAL_SECONDS,

                    "hr_filename_a":
                        group.loc[i, "hr_filename"],

                    "hr_filename_b":
                        group.loc[i + 1, "hr_filename"],
                }
            )

    pair_df = pd.DataFrame(rows)

    print(
        "Temporal transitions:",
        format_number(len(pair_df)),
    )

    if len(pair_df) > 0:

        adjacent_count = int(
            pair_df[
                "is_temporally_adjacent"
            ].sum()
        )

        print(
            "Adjacent transitions:",
            format_number(adjacent_count),
        )

        print(
            "Non-adjacent transitions:",
            format_number(
                len(pair_df) - adjacent_count
            ),
        )

    return pair_df


# ============================================================
# DATASET-LEVEL SUMMARY
# ============================================================

def compute_dataset_summary(
    df: pd.DataFrame,
    video_stats: pd.DataFrame,
    gap_df: pd.DataFrame,
    pair_df: pd.DataFrame,
    duplicate_df: pd.DataFrame,
) -> Dict:

    num_frames = len(df)

    num_videos = int(
        df["video_id"].nunique()
    )

    num_shards = int(
        df["shard"].nunique()
    )

    split_frame_counts = (
        df["split"]
        .value_counts()
        .sort_index()
        .to_dict()
    )

    split_video_counts = (
        df
        .groupby("split")["video_id"]
        .nunique()
        .sort_index()
        .to_dict()
    )

    videos_spanning_shards = int(
        video_stats[
            "spans_multiple_shards"
        ].sum()
    )

    videos_with_gaps = int(
        video_stats[
            "has_frame_id_gap"
        ].sum()
    )

    total_expected_transitions = int(
        video_stats[
            "expected_transitions"
        ].sum()
    )

    total_adjacent_transitions = int(
        video_stats[
            "adjacent_transitions"
        ].sum()
    )

    global_continuity = (
        total_adjacent_transitions
        / total_expected_transitions
        if total_expected_transitions > 0
        else 1.0
    )

    summary = {
        "analysis": "temporal_structure",

        "configuration": {
            "expected_frame_interval_seconds":
                EXPECTED_FRAME_INTERVAL_SECONDS,
        },

        "dataset": {
            "num_frames": num_frames,
            "num_videos": num_videos,
            "num_shards": num_shards,
        },

        "splits": {
            "frames": {
                str(k): int(v)
                for k, v in split_frame_counts.items()
            },

            "videos": {
                str(k): int(v)
                for k, v in split_video_counts.items()
            },
        },

        "temporal_structure": {
            "total_transitions":
                int(len(pair_df)),

            "expected_transitions":
                total_expected_transitions,

            "adjacent_transitions":
                total_adjacent_transitions,

            "global_continuity_ratio":
                float(global_continuity),

            "videos_with_frame_id_gaps":
                videos_with_gaps,

            "total_temporal_gap_locations":
                int(len(gap_df)),
        },

        "video_statistics": {
            "mean_frames_per_video":
                float(
                    video_stats["num_frames"].mean()
                ),

            "median_frames_per_video":
                float(
                    video_stats["num_frames"].median()
                ),

            "min_frames_per_video":
                int(
                    video_stats["num_frames"].min()
                ),

            "max_frames_per_video":
                int(
                    video_stats["num_frames"].max()
                ),

            "mean_estimated_duration_seconds":
                float(
                    video_stats[
                        "estimated_duration_seconds"
                    ].mean()
                ),

            "median_estimated_duration_seconds":
                float(
                    video_stats[
                        "estimated_duration_seconds"
                    ].median()
                ),

            "videos_spanning_multiple_shards":
                videos_spanning_shards,
        },

        "integrity_checks": {
            "duplicate_temporal_identities":
                int(len(duplicate_df)),

            "videos_with_frame_id_gaps":
                videos_with_gaps,

            "temporal_structure_pass":
                (
                    len(duplicate_df) == 0
                    and videos_with_gaps == 0
                ),
        },
    }

    return summary


# ============================================================
# FIGURES
# ============================================================

def save_frames_per_video_figure(
    video_stats: pd.DataFrame,
    output_path: Path,
) -> None:

    values = (
        video_stats["num_frames"]
        .sort_values()
        .reset_index(drop=True)
    )

    if len(values) > MAX_INDIVIDUAL_VIDEOS_IN_PLOT:

        indices = np.linspace(
            0,
            len(values) - 1,
            MAX_INDIVIDUAL_VIDEOS_IN_PLOT,
            dtype=int,
        )

        values = values.iloc[
            indices
        ]

    plt.figure(
        figsize=(12, 6)
    )

    plt.plot(
        range(1, len(values) + 1),
        values,
        marker=".",
        linewidth=1,
    )

    plt.xlabel(
        "Videos (sorted by number of frames)"
    )

    plt.ylabel(
        "Number of frames"
    )

    plt.title(
        "Frames per Video"
    )

    plt.grid(
        True,
        alpha=0.3,
    )

    plt.tight_layout()

    plt.savefig(
        output_path,
        dpi=200,
    )

    plt.close()


def save_frame_gap_distribution_figure(
    video_stats: pd.DataFrame,
    output_path: Path,
) -> None:

    values = (
        video_stats["mean_frame_id_gap"]
        .replace(
            [np.inf, -np.inf],
            np.nan,
        )
        .dropna()
    )

    plt.figure(
        figsize=(10, 6)
    )

    plt.hist(
        values,
        bins=30,
    )

    plt.xlabel(
        "Mean frame-ID gap per video"
    )

    plt.ylabel(
        "Number of videos"
    )

    plt.title(
        "Distribution of Mean Frame-ID Gaps"
    )

    plt.grid(
        True,
        alpha=0.3,
    )

    plt.tight_layout()

    plt.savefig(
        output_path,
        dpi=200,
    )

    plt.close()


def save_duration_figure(
    video_stats: pd.DataFrame,
    output_path: Path,
) -> None:

    values = (
        video_stats[
            "estimated_duration_seconds"
        ]
        .dropna()
    )

    plt.figure(
        figsize=(10, 6)
    )

    plt.hist(
        values,
        bins=30,
    )

    plt.xlabel(
        "Estimated sequence duration (seconds)"
    )

    plt.ylabel(
        "Number of videos"
    )

    plt.title(
        "Estimated Video Duration Distribution"
    )

    plt.grid(
        True,
        alpha=0.3,
    )

    plt.tight_layout()

    plt.savefig(
        output_path,
        dpi=200,
    )

    plt.close()


def save_videos_per_split_figure(
    df: pd.DataFrame,
    output_path: Path,
) -> None:

    values = (
        df
        .groupby("split")["video_id"]
        .nunique()
        .sort_index()
    )

    plt.figure(
        figsize=(8, 6)
    )

    plt.bar(
        values.index.astype(str),
        values.values,
    )

    plt.xlabel(
        "Dataset split"
    )

    plt.ylabel(
        "Number of unique videos"
    )

    plt.title(
        "Videos per Split"
    )

    plt.grid(
        axis="y",
        alpha=0.3,
    )

    plt.tight_layout()

    plt.savefig(
        output_path,
        dpi=200,
    )

    plt.close()


def save_videos_spanning_shards_figure(
    video_stats: pd.DataFrame,
    output_path: Path,
) -> None:

    counts = (
        video_stats[
            "spans_multiple_shards"
        ]
        .value_counts()
        .reindex(
            [False, True],
            fill_value=0,
        )
    )

    labels = [
        "One shard",
        "Multiple shards",
    ]

    values = counts.values

    plt.figure(
        figsize=(8, 6)
    )

    plt.bar(
        labels,
        values,
    )

    plt.xlabel(
        "Shard distribution"
    )

    plt.ylabel(
        "Number of videos"
    )

    plt.title(
        "Videos Spanning Multiple Dataset Shards"
    )

    plt.grid(
        axis="y",
        alpha=0.3,
    )

    plt.tight_layout()

    plt.savefig(
        output_path,
        dpi=200,
    )

    plt.close()


# ============================================================
# SAVE RESULTS
# ============================================================

def save_results(
    output_dirs: Dict[str, Path],
    summary: Dict,
    video_stats: pd.DataFrame,
    gap_df: pd.DataFrame,
    pair_df: pd.DataFrame,
) -> None:

    statistics_dir = output_dirs[
        "statistics"
    ]

    print_step("Saving temporal analysis results")

    # --------------------------------------------------------
    # JSON summary
    # --------------------------------------------------------

    summary_path = (
        statistics_dir
        / "temporal_summary.json"
    )

    with open(
        summary_path,
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            summary,
            f,
            indent=2,
            ensure_ascii=False,
        )

    print(
        f"Saved: {summary_path}"
    )

    # --------------------------------------------------------
    # Video statistics
    # --------------------------------------------------------

    video_path = (
        statistics_dir
        / "video_temporal_statistics.csv"
    )

    video_stats.to_csv(
        video_path,
        index=False,
    )

    print(
        f"Saved: {video_path}"
    )

    # --------------------------------------------------------
    # Temporal gaps
    # --------------------------------------------------------

    gap_path = (
        statistics_dir
        / "temporal_gaps.csv"
    )

    gap_df.to_csv(
        gap_path,
        index=False,
    )

    print(
        f"Saved: {gap_path}"
    )

    # --------------------------------------------------------
    # Frame pairs
    # --------------------------------------------------------

    pair_path = (
        statistics_dir
        / "frame_pair_statistics.csv"
    )

    pair_df.to_csv(
        pair_path,
        index=False,
    )

    print(
        f"Saved: {pair_path}"
    )


# ============================================================
# FINAL REPORT
# ============================================================

def print_final_report(
    summary: Dict,
    runtime_seconds: float,
    output_dirs: Dict[str, Path],
) -> None:

    print_header(
        "FINAL TEMPORAL STRUCTURE REPORT"
    )

    dataset = summary["dataset"]
    temporal = summary["temporal_structure"]
    videos = summary["video_statistics"]
    integrity = summary["integrity_checks"]

    print(
        f"Frames: "
        f"{format_number(dataset['num_frames'])}"
    )

    print(
        f"Videos: "
        f"{format_number(dataset['num_videos'])}"
    )

    print(
        f"Shards: "
        f"{format_number(dataset['num_shards'])}"
    )

    print()

    print(
        f"Temporal transitions: "
        f"{format_number(temporal['total_transitions'])}"
    )

    print(
        f"Adjacent transitions: "
        f"{format_number(temporal['adjacent_transitions'])}"
    )

    print(
        f"Global continuity ratio: "
        f"{temporal['global_continuity_ratio']:.6f}"
    )

    print()

    print(
        f"Videos with frame-ID gaps: "
        f"{format_number(temporal['videos_with_frame_id_gaps'])}"
    )

    print(
        f"Videos spanning multiple shards: "
        f"{format_number(videos['videos_spanning_multiple_shards'])}"
    )

    print()

    print(
        f"Mean frames/video: "
        f"{videos['mean_frames_per_video']:.2f}"
    )

    print(
        f"Median frames/video: "
        f"{videos['median_frames_per_video']:.2f}"
    )

    print(
        f"Min frames/video: "
        f"{videos['min_frames_per_video']}"
    )

    print(
        f"Max frames/video: "
        f"{videos['max_frames_per_video']}"
    )

    print()

    if integrity["temporal_structure_pass"]:

        print(
            "CORE TEMPORAL STRUCTURE: PASS"
        )

    else:

        print(
            "CORE TEMPORAL STRUCTURE: REVIEW REQUIRED"
        )

    print()

    print(
        f"Runtime: "
        f"{runtime_seconds / 60:.2f} minutes"
    )

    print()

    print(
        "Results saved to:"
    )

    print(
        f"  {output_dirs['statistics']}"
    )

    print(
        f"  {output_dirs['figures']}"
    )


# ============================================================
# MAIN
# ============================================================

def main() -> None:

    start_time = time.time()

    print_header(
        "TEMPORAL STRUCTURE ANALYSIS"
    )

    print(
        "PhySense-Human Research Pipeline"
    )

    print(
        "Stage: 02_temporal_redundancy / 01_temporal_structure"
    )

    # --------------------------------------------------------
    # Project root
    # --------------------------------------------------------

    project_root = find_project_root()

    print()
    print(
        f"Project root:\n{project_root}"
    )

    # --------------------------------------------------------
    # Master index
    # --------------------------------------------------------

    master_index_path = find_master_index(
        project_root
    )

    # --------------------------------------------------------
    # Output directories
    # --------------------------------------------------------

    output_dirs = create_output_directories(
        project_root
    )

    # --------------------------------------------------------
    # Load data
    # --------------------------------------------------------

    df = load_master_index(
        master_index_path
    )

    # --------------------------------------------------------
    # Duplicate check
    # --------------------------------------------------------

    duplicate_df = (
        check_duplicate_temporal_identities(
            df
        )
    )

    # --------------------------------------------------------
    # Video statistics
    # --------------------------------------------------------

    video_stats, gap_df = (
        compute_video_temporal_statistics(
            df
        )
    )

    # --------------------------------------------------------
    # Adjacent pairs
    # --------------------------------------------------------

    pair_df = (
        build_adjacent_frame_statistics(
            df
        )
    )

    # --------------------------------------------------------
    # Dataset summary
    # --------------------------------------------------------

    summary = compute_dataset_summary(
        df=df,
        video_stats=video_stats,
        gap_df=gap_df,
        pair_df=pair_df,
        duplicate_df=duplicate_df,
    )

    # --------------------------------------------------------
    # Figures
    # --------------------------------------------------------

    print_step("Generating temporal figures")

    figures_dir = output_dirs[
        "figures"
    ]

    save_frames_per_video_figure(
        video_stats,
        figures_dir
        / "frames_per_video_temporal.png",
    )

    save_frame_gap_distribution_figure(
        video_stats,
        figures_dir
        / "frame_gap_distribution.png",
    )

    save_duration_figure(
        video_stats,
        figures_dir
        / "estimated_video_duration.png",
    )

    save_videos_per_split_figure(
        df,
        figures_dir
        / "videos_per_split_temporal.png",
    )

    save_videos_spanning_shards_figure(
        video_stats,
        figures_dir
        / "videos_spanning_shards.png",
    )

    print(
        "Figures generated."
    )

    # --------------------------------------------------------
    # Save
    # --------------------------------------------------------

    save_results(
        output_dirs=output_dirs,
        summary=summary,
        video_stats=video_stats,
        gap_df=gap_df,
        pair_df=pair_df,
    )

    # --------------------------------------------------------
    # Final report
    # --------------------------------------------------------

    runtime_seconds = (
        time.time() - start_time
    )

    print_final_report(
        summary=summary,
        runtime_seconds=runtime_seconds,
        output_dirs=output_dirs,
    )


if __name__ == "__main__":
    try:
        main()

    except KeyboardInterrupt:

        print()
        print(
            "Process interrupted by user."
        )

        sys.exit(1)

    except Exception as exc:

        print()
        print("=" * 78)
        print("ERROR")
        print("=" * 78)

        print(
            str(exc)
        )

        raise